# Generated by Django 4.0.4 on 2022-05-29 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Аватар')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Широта (в градусах)')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Долгота (в градусах)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_profile', models.ForeignKey(help_text='Профиль пользователя, которому понравился другой пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='main_profile', to='mainapp.profile', verbose_name='Основной профиль профиль')),
                ('profile', models.ForeignKey(help_text='Профиль понравившегося пользователя', on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile', verbose_name='Второй профиль')),
            ],
        ),
    ]
